### ISSUE TITLE
PyPI package?

### ISSUE THREAD

**Issue by ronichoudhury** [getify/JSON.minify#21]
Thanks for creating this utility.  I was wondering if there are plans to make a python package to PyPI, so that clients can install via tools like `pip`.  That would be pretty great.

**Comment by pradyun** [comment]
@ronichoudhury This will happen after #23 is completed and closed.

**Comment by ronichoudhury** [comment]
Ah, good news!  Thanks again for JSON.minify!

**Comment by pradyunsg** [comment]
#26 adds all the necessary components for adding the package to PyPI. Expect this issue to be closed soon.

**Comment by pradyunsg** [comment]
Just to annoy everyone with another notification.

@getify Who should be the one publishing the package on PyPI?

**Comment by getify** [comment]
I don't do anything in the python world (don't even know really what PyPI is), so it wouldn't be me... someone who's invested in the python community seems like the appropriate party to do so.

**Comment by pradyunsg** [comment]
@ronichoudhury I'll do this over this weekend.

**Comment by tobeycarman** [comment]
Any progress on this? I haven't been able to find the package on PyPI.

**Comment by pradyunsg** [comment]
Nope. I had exams (still do, one tomorrow) so couldn't take out the time.

**Comment by tobeycarman** [comment]
Ah, I see. I would be happy take on this issue, but I would need a few hints about how/where to start, as I haven't ever prepared anything for PyPI before and don't really know how it is supposed to work.
Good luck with you exams!

**Comment by johanneswilm** [comment]
Hey @pradyunsg how are your exams going? ;-) Could you publish the package now? It seems all other packages with this functionality are totally outdated. it shouldn't take more than a few minutes. Let me know if you cannot do it, then I or someone else will have to push one of the other ones.

**Comment by johanneswilm** [comment]
How about you, @PoByBolek? I noticed you were the last one committing a patch to the project. Would you mind doing the PyPi package if no-one else here is willing to do it?

**Comment by pradyunsg** [comment]
> Hey @pradyunsg how are your exams going? ;-)

The hilarious part is - still ongoing.

**Comment by pradyunsg** [comment]
btw - you can use the current python branch as follows:

```
pip install git+https://github.com/getify/JSON.minify@python
```

**Comment by johanneswilm** [comment]
Yes, I know. but we need to release, and then we don't want to depend on repo names or even commits on github as they could be gone at any time.

**Comment by johanneswilm** [comment]
@getify @pradyunsg As you know, I created and uploaded that package [1] because this issue had not been dealt with for two years. I also added you to pypi to be able to create new releases. From your messages here it sounded like you agreed with this plan. You now changed the readme to say that there is no package on pypi -- what's the point of that? Please, just change the readme back or even better: mention the package on pypi there. You don't really need to do anything other other than changing the readme as it's all set up to work already.

The one change you requested [1], @pradyunsg , sounds like you have a faulty python installation on Windows (?), but you are more than welcome to do that change yourself if you really think it is a good idea. 

[1] https://pypi.python.org/pypi/JSON_minify/0.2.1
[2] https://github.com/getify/JSON.minify/pull/43

**Comment by pradyunsg** [comment]
> sounds like you have a faulty python installation on Windows

I don't. I was wanting to do defensive coding. But what you're saying is fine with me. :)

**Comment by pradyunsg** [comment]
We have this now.
